export const commandCategories = [
  { id: "general", name: "General" },
  { id: "erlc", name: "ER:LC" },
  { id: "events", name: "Events" },
];

export const commands = [
  {
    name: "/ping",
    category: "general",
    description: "Check bot latency and API responsiveness",
    usage: "/ping",
    permissions: "None",
    example: "/ping",
  },
  {
    name: "/prefix",
    category: "general",
    description: "Change the custom bot prefix for your server",
    usage: "/prefix <new_prefix>",
    permissions: "Manage Server",
    example: "/prefix !",
  },
  {
    name: "/server",
    category: "general",
    description: "Display live ER:LC server status, player count, and queue",
    usage: "/server",
    permissions: "None",
    example: "/server",
  },
  {
    name: "/setup",
    category: "general",
    description:
      "Launch the guided setup wizard to configure channels and roles",
    usage: "/setup",
    permissions: "Manage Server",
    example: "/setup",
  },
  {
    name: "/erlc command",
    category: "erlc",
    description: "Run approved remote ER:LC commands directly via Discord",
    usage: "/erlc command <command>",
    permissions: "Manage Server",
    example: "/erlc command kick David 3",
  },
  {
    name: "/events create",
    category: "events",
    description: "Create and save a new automated event preset",
    usage: "/events create <type>",
    permissions: "Manage Events",
    example: "/events create type:Murder Mystery",
  },
  {
    name: "/events edit",
    category: "events",
    description: "Edit an existing saved event configuration preset",
    usage: "/events edit <preset_id>",
    permissions: "Manage Events",
    example: "/events edit preset:3",
  },
  {
    name: "/events delete",
    category: "events",
    description: "Delete a saved event preset from your server database",
    usage: "/events delete <preset_id>",
    permissions: "Manage Events",
    example: "/events delete preset:3",
  },
  {
    name: "/events list",
    category: "events",
    description: "List all currently saved event presets in your server",
    usage: "/events list",
    permissions: "None",
    example: "/events list",
  },
  {
    name: "/events info",
    category: "events",
    description: "Display detailed configuration info for a specific event",
    usage: "/events info <preset_id>",
    permissions: "None",
    example: "/events info preset:1",
  },
  {
    name: "/events start",
    category: "events",
    description: "Launch a saved event preset and start automated management",
    usage: "/events start <preset_id>",
    permissions: "Manage Events",
    example: "/events start preset:1",
  },
  {
    name: "/events end",
    category: "events",
    description: "Manually end a currently running automated event",
    usage: "/events end",
    permissions: "Manage Events",
    example: "/events end",
  },
];
